### ISSUE TITLE
Customer view: Navbar

### ISSUE THREAD

**Issue by felipecustodio** [dnery/pet-shop-app#18]
- [x] ["Kill the hamburger menu"](https://techcrunch.com/2014/05/24/before-the-hamburger-button-kills-you/)

- [x] Icons for shopping cart and login 

Suggested format:

- [x] LOGO | Products Services Shopping Cart User

**Comment by dnery** [comment]
The hamburger menu currently shows only on medium-sized or smaller devices (below **md** starting breakpoint). Should we replace it either way?

(For the record)
![image](https://user-images.githubusercontent.com/12429434/41214952-461e07e6-6d24-11e8-8e8a-9807ce5d86ea.png)

**Comment by felipecustodio** [comment]
Let's keep it for mobile / smaller screens
