### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by felipecustodio** [dnery/pet-shop-app#19]
- [ ] Smaller banner, no margins, some cool impact text
	- [ ] In case that's not possible, we can make one on photoshop quickly

![image](https://user-images.githubusercontent.com/4261743/41206232-907f6b10-6cd7-11e8-8027-53d60ae1b127.png)

- [x] We could change to something like this

![image](https://user-images.githubusercontent.com/4261743/41206333-c07fb0da-6cd8-11e8-9197-1ff7357c1563.png)

- [ ] Make cards smaller and centered, with more padding between them

![image](https://user-images.githubusercontent.com/4261743/41206359-25eb029e-6cd9-11e8-8a14-5eb150b46d46.png)

- [ ] Keep button highlighted so we know which page we're on

![image](https://user-images.githubusercontent.com/4261743/41206370-47a7403c-6cd9-11e8-8cc2-f10cf1f748b0.png)

- [ ] Show which page we're on on the bar (also, a logo on the bar would be nice, I'll sketch one)

![image](https://user-images.githubusercontent.com/4261743/41206378-80a300a6-6cd9-11e8-8376-2aaafedc8bb3.png)

- [x] Buttons need explanations

![image](https://user-images.githubusercontent.com/4261743/41206395-d2852c82-6cd9-11e8-9db9-08739bfbd817.png)

- [x] Fix this criminal purple

![image](https://user-images.githubusercontent.com/4261743/41206404-f050af3e-6cd9-11e8-891c-bbee42b79e51.png)

- [x] Item photo alongside the description

![image](https://user-images.githubusercontent.com/4261743/41206410-03e3ce14-6cda-11e8-8a06-8f651d1aee57.png)

- [x] Can this outline be removed?

![image](https://user-images.githubusercontent.com/4261743/41206205-10e096f4-6cd7-11e8-9a64-c19c6d1fa311.png)

**Comment by dnery** [comment]
Updated banner, brought the old text button menu back. Other updates underway.

**Comment by felipecustodio** [comment]
On 'Meus Pets', we need the same warning as 'Meus Agendamentos', that nothing exists. 

![image](https://user-images.githubusercontent.com/4261743/41229159-6499ba30-6d51-11e8-910b-2a77e0d70bc3.png)

![image](https://user-images.githubusercontent.com/4261743/41229205-82a34172-6d51-11e8-84d8-6a706eac7d0e.png)

**Comment by felipecustodio** [comment]
Maybe use only photos or only icons? For consistency

![image](https://user-images.githubusercontent.com/4261743/41229245-9f56baf6-6d51-11e8-921b-31e1b2849bd9.png)
